name: CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  bump-version:
    if: ${{ github.actor != 'briskhome-bot' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Bump version
      uses: ./.github/actions/bump-version
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
