# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*.*.*'

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bump version
      uses: ./.github/actions/bump-version
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      if: ${{ github.actor != 'osome-bot' }}
