# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        persist-credentials: yes

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Bump version
      uses: ./.github/actions/bump-version
      with:
        actor: briskhome-bot
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    # - name: Run a multi-line script
    #   run: |
    #     git remote add github "https://briskhome-bot:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
    #     git pull github ${GITHUB_REF} --ff-only

    #     git config user.email "hello@briskhome.com"
    #     git config user.name "Briskhome Bot"


    #     npm version minor --no-git-tag-version
    #     git add package.json
    #     VERSION=$(jq < package.json .version -r)

    #     git commit -m "v$VERSION"
    #     git push github HEAD:${GITHUB_REF}

