name: CI

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'package.json'
    tags-ignore:
      - 'v*.*.*'

jobs:
  bump-version:
    if: ${{ github.actor != 'osome-bot' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.OSOME_BOT_TOKEN }}

    - name: Bump application version
      uses: 'OsomePteLtd/actions/packages/bump-version@master'
      with:
        token: ${{ secrets.OSOME_BOT_TOKEN }}

