# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*.*.*'

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bump version
      uses: ./.github/actions/bump-version
      with:
        actor: osome-bot
        token: ${{ secrets.OSOME_BOT_TOKEN }}
      if: ${{ github.actor != 'osome-bot' }}

    # - name: Run a multi-line script
    #   run: |
    #     git remote add github "https://briskhome-bot:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
    #     git pull github ${GITHUB_REF} --ff-only

    #     git config user.email "hello@briskhome.com"
    #     git config user.name "Briskhome Bot"


    #     npm version minor --no-git-tag-version
    #     git add package.json
    #     VERSION=$(jq < package.json .version -r)

    #     git commit -m "v$VERSION"
    #     git push github HEAD:${GITHUB_REF}

